version: "3.9"

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin1admin1"
      POSTGRES_DB: "rssagg"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rssagg:
    image: rssagg:dev
    ports:
      - "8000:${PORT}"
    build:
      dockerfile: ./Dockerfile
      context: .
    env_file:
      - "./docker.env"

volumes:
  postgres_data:
